name: Build GYM Android APK
  on:
    push:
      branches: [main]
    workflow_dispatch:

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          python -m pip install --upgrade pip
          pip install buildozer cython

      - name: Fix buildozer.spec
        run: |
          sed -i 's/android.ndk = 23b/android.ndk = 25b/' buildozer.spec
          sed -i 's/android.api = 29/android.api = 30/' buildozer.spec
          sed -i 's/armeabi-v7a/arm64-v8a/' buildozer.spec
          sed -i 's/requirements = python3==3.9.16,kivy==2.1.0,openpyxl==3.0.10,cython==0.29.33/requirements = python3,kivy,openpyxl/' buildozer.spec

      - name: Build APK
        run: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: gym-app-apk
          path: bin/*.apk
