name: Build Android APK
  on:
    push:
      branches: [ main ]
    workflow_dispatch:

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk wget
          pip install buildozer cython==0.29.33

      - name: Setup Android SDK
        run: |
          mkdir -p $HOME/.buildozer/android/platform
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip -q commandlinetools-linux-11076708_latest.zip -d $HOME/.buildozer/android/platform/
          mv $HOME/.buildozer/android/platform/cmdline-tools $HOME/.buildozer/android/platform/android-sdk/

      - name: Build APK
        run: |
          export ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk
          export PATH=$PATH:$ANDROID_HOME/bin
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: gym-app-apk
          path: bin/*.apk

