name: Build APK

on:
  push:
    branches: [ main, develop, claude/** ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 90

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Free space (fast)
        timeout-minutes: 5
        run: |
          df -h
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /usr/local/.ghcup &
          sudo docker image prune -af &
          wait
          df -h

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install system deps
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends \
            build-essential git wget unzip zip \
            python3-pip python3-setuptools \
            autoconf automake libtool \
            libssl-dev libffi-dev \
            libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
            openjdk-17-jdk

      - name: Install buildozer
        run: |
          pip3 install --upgrade pip setuptools wheel
          pip3 install buildozer cython python-for-android

      - name: Cache buildozer
        uses: actions/cache@v4
        with:
          path: |
            ~/.buildozer
            ~/.gradle
          key: buildozer-${{ runner.os }}-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            buildozer-${{ runner.os }}-

      - name: Build APK
        env:
          GRADLE_OPTS: "-Xmx2048m -Dorg.gradle.jvmargs='-Xmx2048m'"
        run: |
          buildozer -v android debug 2>&1 | tee build.log

      - name: Check build result
        run: |
          if ls bin/*.apk 1> /dev/null 2>&1; then
            echo "✓ APK built successfully"
            ls -lh bin/*.apk
          else
            echo "✗ Build failed"
            echo "=== SEARCHING FOR ERRORS ==="
            grep -i "error" build.log | tail -50 || true
            echo "=== LAST 500 LINES ==="
            tail -500 build.log
            exit 1
          fi

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: IGCSE-GYM-${{ github.run_number }}
          path: bin/*.apk

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs-${{ github.run_number }}
          path: build.log
