name: Build GYM APK
  on: [workflow_dispatch]

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - name: Setup
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install --user kivy[base] buildozer cython
      - name: Build
        run: |
          echo "[app]
          title = GYM
          package.name = gymtracker
          package.domain = com.fitness.gymtracker
          source.dir = .
          source.include_exts = py,png,jpg,kv,atlas,json
          version = 1.0.0
          source.main = main_android.py
          requirements = python3,kivy
          android.api = 30
          android.minapi = 21
          android.ndk = 25b
          android.archs = arm64-v8a
          p4a.branch = master
          p4a.bootstrap = sdl2
          android.accept_sdk_license = True
          [buildozer]
          log_level = 2" > buildozer.spec
          ~/.local/bin/buildozer android debug
      - uses: actions/upload-artifact@v4
        with:
          name: gym-apk
          path: bin/*.apk
