 name: Build GYM APK
  on: [workflow_dispatch]

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          python -m pip install --upgrade pip
          pip install buildozer cython
          buildozer android debug
      - uses: actions/upload-artifact@v4
        with:
          name: gym-apk
          path: bin/*.apk
